# Generated by Django 2.2.6 on 2021-10-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("content", models.TextField(verbose_name="日报内容")),
                ("create_by", models.CharField(max_length=128, verbose_name="创建人")),
                ("date", models.DateTimeField(verbose_name="日报日期")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyReportTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="日报模板名字")),
                ("content", models.CharField(max_length=255, verbose_name="日报模板内容")),
                ("create_by", models.CharField(max_length=128, verbose_name="创建人")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="组名字")),
                ("admin", models.CharField(max_length=255, verbose_name="管理员们")),
                ("create_by", models.CharField(max_length=128, verbose_name="创建人")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupNotifier",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(verbose_name="组id")),
                ("daily_notifier_id", models.IntegerField(verbose_name="日报通知人")),
            ],
        ),
        migrations.CreateModel(
            name="GroupUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(verbose_name="组id")),
                ("user_id", models.IntegerField(verbose_name="用户id")),
            ],
        ),
        migrations.CreateModel(
            name="TemplateGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(verbose_name="组id")),
                ("template_id", models.IntegerField(verbose_name="模板id")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("username", models.CharField(max_length=128, unique=True, verbose_name="用户账号")),
                ("name", models.CharField(max_length=128, verbose_name="用户姓名")),
                ("gender", models.IntegerField(null=True, verbose_name="性别")),
                ("phone", models.IntegerField(null=True, verbose_name="电话号码")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]