# Generated by Django 2.2.6 on 2021-10-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(blank=True, choices=[(0, "男"), (1, "女")], null=True, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(blank=True, null=True, verbose_name="电话号码"),
        ),
    ]
