# Generated by Django 2.2.6 on 2021-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0005_auto_20211025_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="send_status",
            field=models.BooleanField(default=False, verbose_name="发送状态"),
            preserve_default=False,
        ),
    ]
