# Generated by Django 2.2.6 on 2021-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0006_daily_send_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="create_name",
            field=models.CharField(default=1, max_length=128, verbose_name="创建人姓名"),
            preserve_default=False,
        ),
    ]
