# Generated by Django 2.2.6 on 2021-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0009_dailyreporttemplate_create_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="template_id",
            field=models.IntegerField(default=1, verbose_name="模板id"),
            preserve_default=False,
        ),
    ]
