# Generated by Django 2.2.6 on 2021-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0010_daily_template_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyJoinGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField(verbose_name="组id")),
                ("user_id", models.IntegerField(verbose_name="用户id")),
            ],
            options={
                "unique_together": {("group_id", "user_id")},
            },
        ),
    ]
