# Generated by Django 2.2.6 on 2021-11-23 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0011_applyjoingroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjoingroup",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="创建时间"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applyjoingroup",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
