# Generated by Django 2.2.6 on 2021-11-27 20:07

import django_mysql.models
from django.db import migrations

import home_application.models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0011_applyforgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="evaluate",
            field=django_mysql.models.JSONField(
                default=home_application.models.daily.daily_evaluate_default, verbose_name="评价"
            ),
        ),
    ]
