# Generated by Django 2.2.6 on 2021-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0012_daily_evaluate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily",
            name="send_status",
            field=models.BooleanField(default=False, verbose_name="发送状态"),
        ),
    ]
