# Generated by Django 2.2.6 on 2021-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0013_auto_20211128_1040"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                ("day", models.IntegerField(verbose_name="日期")),
                ("is_holiday", models.BooleanField(verbose_name="是否为节假日")),
                ("note", models.CharField(max_length=255, verbose_name="备注")),
            ],
            options={
                "unique_together": {("year", "month", "day")},
            },
        ),
    ]
