# Generated by Django 2.2.6 on 2021-11-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0013_auto_20211128_1040"),
    ]

    operations = [
        migrations.CreateModel(
            name="Off_day",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("off_day_date", models.DateField(verbose_name="请假日期")),
                ("deadline", models.DateField(verbose_name="截至日期")),
                ("reason", models.TextField(verbose_name="请假理由")),
                ("off_by", models.CharField(max_length=128, verbose_name="请假人用户名")),
                ("off_name", models.CharField(max_length=128, verbose_name="请假人姓名")),
                ("off_status", models.BooleanField(default=True, verbose_name="请假状态")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
