# Generated by Django 2.2.6 on 2021-11-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0013_auto_20211124_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyforgroup",
            name="operator",
            field=models.IntegerField(null=True, verbose_name="处理人id"),
        ),
    ]
