# Generated by Django 2.2.6 on 2021-12-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0014_holiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffDay",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("start_date", models.DateField(verbose_name="请假开始日期")),
                ("end_date", models.DateField(verbose_name="请假结束日期")),
                ("reason", models.TextField(verbose_name="请假理由")),
                ("user", models.CharField(max_length=128, verbose_name="请假人用户名")),
            ],
            options={
                "unique_together": {("start_date", "user", "end_date")},
            },
        ),
    ]
