# Generated by Django 2.2.6 on 2021-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0015_auto_20211125_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyforgroup",
            name="status",
            field=models.SmallIntegerField(verbose_name="申请状态"),
        ),
    ]
