# Generated by Django 2.2.6 on 2021-12-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0016_auto_20211209_1522"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeTime",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("start_time", models.DateTimeField(verbose_name="当天有空时间段的起始时间")),
                ("end_time", models.DateTimeField(verbose_name="当天有空时间段的结束时间")),
                ("username", models.CharField(max_length=128, verbose_name="用户名")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
