# Generated by Django 2.2.6 on 2021-12-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0017_freetime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyReportTemplate",
        ),
    ]
