name: eslint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Entry frontend
      run: |
        cd frontend
        ls        
    - name: Install modules
      run: |
        pwd
        npm install
    - name: Run ESLint
      run: eslint --ext .js,.vue src
